# Removes everything `cmake --install` recorded in install_manifest.txt.
# Run via:  sudo cmake --build build --target uninstall
if (NOT EXISTS "${MANIFEST}")
  message(FATAL_ERROR "No install manifest at ${MANIFEST} -- nothing was installed from this build dir.")
endif()
file(STRINGS "${MANIFEST}" _files)
foreach(_f IN LISTS _files)
  if (EXISTS "${_f}" OR IS_SYMLINK "${_f}")
    message(STATUS "Removing ${_f}")
    file(REMOVE "${_f}")
  endif()
endforeach()
# Clean up the plugin directory we own, if it's now empty.
foreach(_f IN LISTS _files)
  if (_f MATCHES "/qqvideo/plugins/")
    get_filename_component(_pdir "${_f}" DIRECTORY)
    get_filename_component(_qdir "${_pdir}" DIRECTORY)
    file(GLOB _left "${_pdir}/*")
    if (NOT _left)
      file(REMOVE_RECURSE "${_pdir}")
      file(GLOB _left2 "${_qdir}/*")
      if (NOT _left2)
        file(REMOVE_RECURSE "${_qdir}")
      endif()
    endif()
    break()
  endif()
endforeach()

# Refresh the shared launcher/icon caches (other apps' entries live there
# too, so they're regenerated, not deleted) so qqvideo drops out of the menu.
foreach(_f IN LISTS _files)
  if (_f MATCHES "/applications/qqvideo\\.desktop$")
    get_filename_component(_appdir "${_f}" DIRECTORY)
    get_filename_component(_datadir "${_appdir}" DIRECTORY)
    find_program(_udd update-desktop-database)
    if (_udd AND EXISTS "${_appdir}")
      execute_process(COMMAND "${_udd}" -q "${_appdir}")
    endif()
    find_program(_gic gtk-update-icon-cache)
    if (_gic AND EXISTS "${_datadir}/icons/hicolor")
      execute_process(COMMAND "${_gic}" -q -t -f "${_datadir}/icons/hicolor" ERROR_QUIET)
    endif()
  endif()
endforeach()
